name: Actions Cleaner

# This is an experiment to see if we can get a better minimal container
# by removing a bunch of things we don't want.

on: 

  # On pull request we test updates to images
  pull_request: []
 
jobs:
  update:
    name: Clean All The Things!
    runs-on: ubuntu-latest
    steps:

      - name: Pre-Size
        run: df -h

      - name: Purge Docker
        run: |
           printf "docker system prune --all --force\n"
           docker system prune --all --force

      - name: Remove Big Installs
        run: |

          comm -23 <(apt-mark showmanual | sort -u) <(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort -u)
          sudo apt purge openjdk-*
          sudo apt remove --autoremove openjdk-*        
          sudo apt purge oracle-java*

          sudo apt-get remove -y podman swift texlive maven r-base-core r-base apache2 azure-cli google-cloud-sdk ant vim
          sudo apt-get autoremove
          printf "sudo rm -rf /usr/share/dotnet\n"
          sudo rm -rf /usr/share/dotnet
          printf "sudo rm -rf /opt/*.zip\n"
          sudo rm -rf /opt/*.zip
          sudo rm -rf /usr/share/*.zip
          printf "sudo rm -rf /opt/*.tar.gz\n"
          sudo rm -rf /opt/*.tar.gz
          sudo rm -rf /usr/share/*.tar.gz
          printf "sudo rm -rf /usr/local/lib/android\n"
          sudo rm -rf /usr/local/lib/android
          printf "sudo rm -rf /opt/ghc\n"
          sudo rm -rf /opt/ghc
          printf "sudo rm -rf /opt/az\n"
          sudo rm -rf /opt/az
          sudo rm -rf /usr/share/az*
          printf "sudo rm -rf /opt/google\n"
          sudo rm -rf /opt/google
          printf "sudo rm -rf /opt/R\n"
          sudo rm -rf /opt/R
          sudo rm -rf /usr/share/R
          printf "sudo rm -rf /opt/microsoft\n"
          sudo rm -rf /opt/microsoft
          tree --du -h -L 3 /opt

      - name: Post-Size
        run: df -h

