name: Actions Cleaner

on: 

  # On pull request we test updates to images
  pull_request: []

jobs:
  test-cleaner:
    name: Test Actions Cleaner
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04

    steps:
      - name: Clean All The Things
        uses: ./ubuntu
