name: Double Cleaner

on: 
  workflow_dispatch

jobs:
  test-cleaner:
    name: Test Actions Cleaner
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean All The Things
        uses: ./ubuntu
